FROM node:18.10-alpine as deps

WORKDIR /app

COPY package*.json ./

RUN npm ci

FROM deps as build

WORKDIR /app

ENV NODE_ENV development
ENV PORT=3000

COPY . ./app

EXPOSE 3000

CMD sh -c "npm run dev"
